name = "nmed-audio-contrastive-v3"
data_path = "/kreka/research/willy/side/brain_datasets/nmed-processed/nmed-train.safetensors"
audio_embeds_path = "/kreka/research/willy/side/brain_datasets/nmed-processed/nmed-train-encodec.safetensors"
dataset = "sparse_audio_embed"
arch = "audio_contrastive"

epochs = 50
batch_size = 256
lr = 3e-4
weight_decay = 0.01
lr_warmup_steps = 100

[audio_contrastive]
encoder_dim = 512
encoder_mlp_dim = 2048
heads = 8
depth = 6
dim_head = 64
dropout = 0.1
num_channels = 120
eeg_samples = 125
audio_embed_dim = 128
audio_frames = 75
audio_encoder_depth = 4
audio_encoder_heads = 8
audio_encoder_dim_head = 64
audio_encoder_mlp_dim = 2048
shared_embed_dim = 256
init_logit_scale = 0.0
max_logit_scale = 4.6052
contrastive_weight = 1.0
mse_weight = 0.0
variance_weight = 1.0
covariance_weight = 0.04
variance_target = 1.0
