name = "nmed-hierarchical-embed-full"
data_path = "/kreka/research/willy/side/brain_datasets/nmed-processed/continuous/full/nmed-train.safetensors"
audio_embeds_path = "/kreka/research/willy/side/brain_datasets/nmed-processed/continuous/full/nmed-train-encodec.safetensors"
lengths_path = "/kreka/research/willy/side/brain_datasets/nmed-processed/continuous/full/nmed-train-lengths.safetensors"
dataset = "continuous_audio_embed"
arch = "hierarchical_audio_embed"
spatial_checkpoint = "checkpoints/nmed-baseline-embed-5ep/final"

epochs = 5
batch_size = 4
lr = 1e-4
weight_decay = 0.01
lr_warmup_steps = 20

[hierarchical_audio_embed]
encoder_dim = 512
encoder_mlp_dim = 2048
heads = 8
depth = 6
dim_head = 64
dropout = 0.1
num_channels = 120
eeg_samples = 125
temporal_dim = 512
temporal_depth = 4
temporal_heads = 8
temporal_dim_head = 64
temporal_mlp_dim = 2048
max_seq_len = 300
audio_embed_dim = 128
audio_frames = 75
